### ISSUE TITLE
Not understandable information in the README file

### ISSUE THREAD

**Issue by camimonse** [auth0-samples/auth0-symfony-php-web-app#12]
**Context:**
- We want to try the PHP Symfony sample from https://auth0.com/docs/quickstart/webapp/symfony
- We download it and open the README file that is inside the folder, and start following the instructions

**Problem:**

We find a step that needs further explanation:

![image](https://cloud.githubusercontent.com/assets/18585436/19699968/594193e0-9ac3-11e6-835b-2977bdf1cd20.png)
- The usage of "_If you just create a file named .env .._." is not a direct instruction, it must be in the imperative form: "_For that, **create** a file named (or called) .env..._"
-  It is unclear to say "_set the values_". Because "_set_" is to put information in an already existing file, but since the .env file doesn't exist, there is no such place to set in. Would be better to say: "copy and paste the following..." or "_**create a new** file with the following... and **save it as an .env file**_"

**Importance:**
- The user doesn't know if that is a file that needs to be done, needs to be found, or could just skip this step.
- Instructions must be clear in order to success opening the sample.

**Comment by camimonse** [comment]
this refers to GitHub ticket number 3359
and is related to #7

**Comment by chenkie** [comment]
Closed by #18

**Comment by camimonse** [comment]
This passed the sanity
